### ISSUE TITLE
Bug - se loger --> renvoie au formulaire de newsletter

### ISSUE THREAD

**Issue by capudav** [betagouv/Ecolab#105]
Quand on clique sur l'onglet "se loger", on tombe sur la newsletter. Est-ce un erreur ou parce que rien n'est encore dispo pour se loger ? Auquel cas, peut être ajouter une mention "en cours de développement, ente temps, tenez-vous au courant en vous abonnant à la newsletter"

**Comment by martinregner** [comment]
Il y a maintenant une page bâtiment :)
