### ISSUE TITLE
[DESIGN] voir comment ajouter les pondérations sur chacun des indicateurs 14

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/Ecolab#134]
2 propositions :

> une première option : mettre un lien sur "détail de la pondération" vers la page du gitbook

> 2ème option : en cliquant sur afficher les pondérations

> combiner les 2 options ?

**Comment by martinregner** [comment]
Pondération faites sur 16 indicateurs, 14 seulement sont affichés (autres présents seulement dans version logiciels ACV)
Action à abandonner
