### ISSUE TITLE
Ajouter logo ADEME/Inrae sur l'image (pour voir le portage dès le début) : en haut à droite de l'image > en bas à droite du nid de tagliatelles ?

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/Ecolab#146]
Logos ADEME/inrae : pour mieux montrer le portage, autant les mettre visible d'emblée, sur la photo AGB (suis ok avec l'argument, c'est ce que viennent chercher les acteurs : une base publique)

**Comment by martinregner** [comment]
ok nouvelle version du site
