### ISSUE TITLE
agribalyse.fr/en vers version ecolab.ademe.fr/en

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/Ecolab#165]

**Comment by JenniferStephan** [comment]
a priori, a checker, je peux faire une redirection sur gandi en mettant un sous-domaine d'agribalyse.fr renvoyant vers notre page ecolab en eng. 
donc pr l'instant eng.agribalyse.fr renvoie vers ecolab.ademe.fr/agribalyse_eng

![Capture d’écran 2020-11-09 à 09 57 18](https://user-images.githubusercontent.com/36134318/98522412-f06a9680-2274-11eb-8a56-7ed7e36e7b1d.png)


a voir pour faire un agribalyse.fr/en vers ecolab.ademe.fr/agribalyse_eng

**Comment by martinregner** [comment]
@JenniferStephan Le renvoi est KO : il y a des https// en trop a priori
Si pas possible avec le nouveau site --> à abandonner

**Comment by martinregner** [comment]
Le nouveau site remplit le besoin

**Comment by martinregner** [comment]
Le nouveau site remplit le besoin
