### ISSUE TITLE
Image pour l'article sur le simulateur transport

### ISSUE THREAD

**Issue by laem** [betagouv/Ecolab#29]
On s'est dit qu'il était mieux de mettre une image d'un mode de transport. 

Suggestion : 

![](https://miro.medium.com/max/1376/1*lgbRWT3Chvu4V_ybv307Yw.jpeg)

(je cherchais une belle photo d'un train et d'un avion pour [un petit article](https://medium.com/@l4em/voie-b-le-tgv-airfrance-n-01072020-est-attendu-au-d%C3%A9part-55f05f86fb42) sur le sujet de l'avenir de l'industrie aérienne)

**Comment by martinregner** [comment]
J'aime bien !
Aussi trouvé, avec surtout du vélo (trop ?) : https://unsplash.com/photos/NNqGUT_Jjlc

Ou du train (mais pas en extérieur...) : https://unsplash.com/photos/03RmsU4i4Ns

**Comment by fjg** [comment]
J'aime bien la tienne @laem mais je pense que le vélo est plus concensuel et plus à l'image de ce qu'on essaie de viser.
La photo avec l'avion peut laisser penser qu'on peut le garder, et le sujet semble "compliqué". Et dernier point le format, elle est trop verticale.

Donc +1 pour le vélo (y'en a jamais trop ;)

**Comment by JenniferStephan** [comment]
de mon côté, pour la bannière de l'article, j'ai : 

1) celle-ci très parisienne avec un peu tous/trop les modes (voitures ++, vélos, motos, et de la marche piétonne) : https://unsplash.com/photos/qzNB3arkZ-w

2) vélo rue de Rennes (un peu tristoune) : https://unsplash.com/photos/7ws-bInH7sc 

3) version multimodale (ma préf) - un vélo parké sur une bouche de métro parisien avec des passants , où on entre-aperçoit un panneau "autolib" : https://unsplash.com/photos/8k9TVauvQ_0

+ pour le teaser rayon d'action en "première proposition" (1024x768) : 

![rayonaction](https://user-images.githubusercontent.com/36134318/79211148-21512d00-7e46-11ea-8172-14cb4e39e05e.png)
