### ISSUE TITLE
Contextualiser la page transport (landing)

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/Ecolab#34]
objectif : rendre plus explicite la démarche, les données, mettre en perspectif
cmt : enrichir le contenu de la page https://ecolab.ademe.fr/transport, aujd uniquement le simulateur

- [x] Bannière transport (cohérente et harmonisée avec alim)
- [x] Textes explicatifs des simulateurs, mise en contexte
- [x] section avec lien vers le blog et les articles
- [x] Mise en avant de l'actu et open lab 1

**Comment by fjg** [comment]
qqs suggestions ;)

- [ ] liens vers repo github + releases/changelog
- [ ] lien vers gitbook carbone
- [ ] prévoir la place pour les autres prototypes (mon rayon d'action, etc.)

**Comment by fjg** [comment]
- [ ] idée folle : ajouter qqs liens + explication si nécessaire vers des ré-utilisateurs (ceux qui ont intégré soit le proto, soit les données)

**Comment by martinregner** [comment]
L'occasion de tester la mise en avant des réutilisateurs en effet (comme on ferra sur alimentation) !

- [ ] Lien avec les stats : montrer tous les réutilisateurs connectés / l'activité de l'iframe (sur la page ou lien vers page stat)

**Comment by JenniferStephan** [comment]
première itération habillage du simulateur sur la page /transport : https://ecolab-demo-landing-tra-mtpvui.herokuapp.com/transport lié à la PR : https://github.com/betagouv/Ecolab/pull/35

**Comment by martinregner** [comment]
Top ! J'aime beaucoup l'illustration, les couleurs !
Juste le 4x4, il me fait un peu tiquer ;)
Propositions pour le remplacer (sans trop bouger le reste si possible) - je te mets les noms des illustrations, pas trouvé comment partager un URL sur undraw 😄 :
⭐ ⭐  Subway
⭐ Modern life

**Comment by fjg** [comment]
Pareil j'aime bcp, bravo pour cette première proposition ;)

Idem le 4x4 => des marcheuses·eurs ? :) ou des bus, tram, train, etc.

Et juste les over sur les boutons sont illisibles (blanc sur blanc)

**Comment by laem** [comment]
Très propre 
Il y a juste un bandeau bleu clair à droite.

**Comment by martinregner** [comment]
> proposition figma : https://www.figma.com/file/DNnz4ZCL13uWLjw6GPDuzh/Ecolab---proto?node-id=94%3A367

J'aime bien la dame "Subway" ! Et avec la trotti devant les arbres je trouve ça encore mieux !😃 👏 

Pour la tagline, pour rester cohérent je propose :
_L'impact **des** déplacements sur le climat
Chiffrer **son** impact et adapter **la** mobilité à des modes de transport moins émetteurs en carbone._

(je propose de retirer "quotidien" pour garder l'avion, le train...)

Bonne idée de garder le même CTA "Parcourez les données" ! 👍 A la recherche tu pensais afficher quoi comme résultat : la "note" du yaml ça peut être pas mal ? (il y a le FE et la source)
Je vois pas trop quoi faire sortir via les blocs (Base Carbone, RATP...) mais tu as peut-être une idée 🤩
