### ISSUE TITLE
Ajouter une licence

### ISSUE THREAD

**Issue by bzg** [betagouv/Ecolab#37]
Parmi les licences autorisées: https://www.data.gouv.fr/fr/licences

Attention: les startups d'Etat utilisent un peu la licence AGPL par réflexe alors que c'est rarement justifié (et justifiable).

Pour un projet de ce genre, je suggère plutôt une licence MIT.

Cf. https://twitter.com/i/status/1252993436204109827 pour le "c'est open source" - il faut alors une licence :)

**Comment by laem** [comment]
En fait ce dépôt est celui du site principal, qui héberge l'iframe transport développé sur betagouv/ecolab-transport qui a bien une license MIT :)

Mais je suis d'accord qu'une license MIT aussi ici ce serait bien

**Comment by bzg** [comment]
Au temps pour moi !
