### ISSUE TITLE
Ajouter une section retours utilisateurs

### ISSUE THREAD

**Issue by fjg** [betagouv/Ecolab#46]
- [ ] demander à Adrien Jeantet (Notre choix)

**Comment by JenniferStephan** [comment]
section carousel témoignages et verbatim de reutilisateurs en prod sur : https://ecolab.ademe.fr/transport
pour ajouter des retex directement sur github : https://github.com/betagouv/Ecolab/blob/master/app/views/pages/transport.html.erb#L123

**Comment by fjg** [comment]
@JenniferStephan il faut mettre dans ton commit un fixed #46 pour que ca ferme l'issue, sinon il faut penser le faire ;-)
