### ISSUE TITLE
[F&L] changer background

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/Ecolab#57]
![Capture d’écran 2020-05-06 à 11 38 49](https://user-images.githubusercontent.com/36134318/81163193-a5528c80-8f8e-11ea-9d10-5f813ac33601.png)

https://ecolab.ademe.fr/alimentation
https://fruit-leg-saisons.herokuapp.com/

**Comment by martinregner** [comment]
Sur mon navigateur le bas de l'iframe est coupé quand c'est "non" (+ de texte).
On peut scroller mais p-e est-il possible de tout afficher ?
![Capture](https://user-images.githubusercontent.com/46482115/81186777-82869f00-8fb3-11ea-9b43-377e0e9b4611.PNG)
