### ISSUE TITLE
CAS D'USAGE 3 Simuler l'impact de son repas/de sa liste de course

### ISSUE THREAD

**Issue by nyck33** [betagouv/Ecolab#98]
I linked here from https://ecolab.ademe.fr/agribalyse after contacting SimaPro about eco-footprint info for various products.

I am a student building an ecofootprint of food web app for my final project and was wondering if you would like to work together on use case 3 in the subject line.  Please respond here or at the following email address:

nobutaka@gatech.edu

PS, I'm very sorry to write in English but my French, which I studied in school in Canada, is very bad.

**Comment by JenniferStephan** [comment]
Hello @nyck33
